apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: diary
  labels:
    app: users
data:
  APP_URL: http://users.diary.localhost
  IDP_URL: http://idp-svc:4444
  IDP_EXTERNAL_URL: http://idp.diary.localhost
  IDP_ADMIN_URL: http://idp-svc:4445
  FRONTEND_URL: http://web.diary.localhost
  APP_DEBUG: "true"
  APP_ENV: production
  APP_NAME: users
  DB_CONNECTION: pgsql
  DB_HOST: db-postgresql.postgres
  DB_PORT: "5432"
  DB_DATABASE: diary
  DB_SCHEMA: users
  DB_USERNAME: diary_user
  GITHUB_CLIENT_ID: 29e23ecfc4eec0814fc0
  IDP_CLIENT_ID: diary-users
