apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: users

namespace: diary

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml

images:
- name: rasouza/diary-users
  newTag: b2d7c20

configMapGenerator:
- envs:
  - envs/app.env
  - envs/urls.env
  name: users-config

secretGenerator:
- envs:
  - envs/db.env
  - envs/credentials.env
  name: users-secret
  type: Opaque
