apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-config
  namespace: diary
data:
  DB_HOST: db-postgresql.postgres
  DB_PORT: "5432"
  DB_DATABASE: diary
  DB_SCHEMA: idp
  DB_USER: diary_idp
  URLS_SELF_ISSUER: http://idp.diary.localhost
  URLS_CONSENT: http://users.diary.localhost/consent
  URLS_LOGIN: http://frontend.diary.localhost/auth/login
  URLS_LOGOUT: http://frontend.diary.localhost/auth/logout
  OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: public,pairwise