apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: core

namespace: diary

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: rasouza/diary-core
  newTag: d46eda9

configMapGenerator:
- envs:
  - envs/app.env
  - envs/urls.env
  name: core-config

generators:
- secret-generator.yaml
