apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: frontend

namespace: diary

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml

images:
- name: rasouza/diary-frontend
  newTag: c8b51cc

configMapGenerator:
- files:
  - envs/default.conf
  name: nginx-config
- files:
  - envs/config.js
  name: env-config
