---
- name: Istio installation
  hosts: localhost
  vars:
    version: 1.6.3
  tasks:
    - name: Download Istio
      shell: curl -L https://istio.io/downloadIstio | sh -
    - name: Move istioctl to /usr/local/bin
      copy:
        src: istio-{{ version }}/bin/istioctl
        dest: /usr/local/bin
    - name: Clean up
      file:
        path: istio-{{ version }}
        state: absent