apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgres

resources:
- namespace.yaml
- secret.yaml
- templates/metrics-svc.yaml
- templates/svc-headless.yaml
- templates/svc.yaml
- templates/statefulset.yaml